version: 0.0
os: linux

files:
  - source: /
    destination: /opt/dev-sesame
permissions:
  - object: /opt/dev-sesame/
    owner: ec2-user
    mode: 755
hooks:
  AfterInstall:
    # location은 프로젝트의 root경로를 기준
    - location: /opt/dev-sesame/deploy.sh
      timeout: 60
      runas: root